# Generated by Django 4.2.30 on 2026-06-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('course_title', models.CharField(max_length=200)),
                ('platform', models.CharField(default='YouTube', max_length=100)),
                ('resource_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
