# Generated by Django 4.2.30 on 2026-06-02 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPortfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('theme_style', models.CharField(choices=[('MODERN', 'Modern Glassmorphic'), ('SKEUOMORPHIC', 'Tactile Skeuomorphic')], default='MODERN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
