# Generated by Django 4.2.30 on 2026-06-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=20)),
                ('category', models.CharField(choices=[('ARRAYS', 'Arrays'), ('STRINGS', 'Strings'), ('LINKED_LISTS', 'Linked Lists'), ('TREES', 'Trees'), ('GRAPHS', 'Graphs'), ('DYNAMIC_PROGRAMMING', 'Dynamic Programming'), ('RECURSION', 'Recursion'), ('SORTING', 'Sorting'), ('SEARCHING', 'Searching'), ('SQL', 'SQL'), ('PYTHON', 'Python'), ('DJANGO', 'Django'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('function_signature', models.CharField(blank=True, max_length=300, null=True)),
                ('starter_code_python', models.TextField(default='# Write your solution here\npass\n')),
                ('starter_code_javascript', models.TextField(default='// Write your solution here\n')),
                ('starter_code_java', models.TextField(default='// Write your solution here\n')),
                ('starter_code_cpp', models.TextField(default='// Write your solution here\n')),
                ('starter_code_csharp', models.TextField(default='// Write your solution here\n')),
                ('visible_test_cases', models.JSONField(blank=True, default=list)),
                ('hidden_test_cases', models.JSONField(blank=True, default=list)),
                ('sample_input', models.TextField(blank=True, null=True)),
                ('sample_output', models.TextField(blank=True, null=True)),
                ('time_limit', models.IntegerField(default=2000)),
                ('memory_limit', models.IntegerField(default=256)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='python', max_length=20)),
                ('submitted_code', models.TextField()),
                ('passed_visible', models.IntegerField(default=0)),
                ('total_visible', models.IntegerField(default=0)),
                ('passed_hidden', models.IntegerField(default=0)),
                ('total_hidden', models.IntegerField(default=0)),
                ('execution_time_ms', models.FloatField(default=0)),
                ('memory_used_mb', models.FloatField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=30)),
                ('score', models.IntegerField(default=0)),
                ('evaluation', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='code_arena.codingchallenge')),
                ('seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', '-evaluated_at'],
            },
        ),
    ]
