# Generated by Django 4.2.30 on 2026-06-18 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_ats_breakdown_application_ats_score_and_more'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interview_schedules', to='jobs.job'),
        ),
    ]
