# Generated by Django 4.2.30 on 2026-06-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ats_breakdown',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='application',
            name='ats_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
