import React from 'react';
import { Link } from 'react-router-dom';
import { Sparkles, ArrowRight, UserCheck, GraduationCap, Building } from 'lucide-react';

export default function Landing() {
  return (
    <div className="space-y-16 py-12 max-w-5xl mx-auto">
      
      {/* Hero Section */}
      <div className="skeuo-card p-12 text-center space-y-6 relative overflow-hidden bg-gradient-to-b from-white to-[#f8fafc] dark:from-[#1e293b] dark:to-[#0f172a]">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full text-xs font-bold bg-blue-500/10 text-blue-500 border border-blue-500/20 glow-active">
          <Sparkles className="w-4.5 h-4.5" />
          <span>Empowered by Groq Llama 3.3 AI</span>
        </div>
        
        <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight leading-tight max-w-3xl mx-auto">
          The Intelligent Bridge Between <span className="bg-gradient-to-r from-blue-600 to-indigo-500 bg-clip-text text-transparent">Talent</span> and <span className="bg-gradient-to-r from-indigo-500 to-teal-500 bg-clip-text text-transparent">Opportunity</span>
        </h1>
        
        <p className="text-base md:text-lg text-slate-500 max-w-2xl mx-auto leading-relaxed">
          AIHire Pro streamlines hiring using deep semantic matching, instant resume structural analysis, and skill gap mapping. Built for developers, trusted by corporate recruiters.
        </p>
        
        <div className="flex flex-wrap items-center justify-center gap-4 pt-4">
          <Link to="/auth" className="skeuo-btn skeuo-btn-primary px-8 py-3.5 text-base">
            <span>Get Started Now</span>
            <ArrowRight className="w-5 h-5" />
          </Link>
          <Link to="/auth" className="skeuo-btn skeuo-btn-secondary px-8 py-3.5 text-base">
            <span>Sign In</span>
          </Link>
        </div>
      </div>

      {/* Features workflow grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Recruiter Card */}
        <div className="skeuo-card p-8 space-y-4">
          <div className="w-12 h-12 rounded-xl bg-teal-500/10 flex items-center justify-center text-teal-600">
            <Building className="w-6 h-6" />
          </div>
          <h3 className="text-2xl font-extrabold">For Corporate Recruiters</h3>
          <p className="text-sm text-slate-500 leading-relaxed">
            Post job descriptions and receive candidates sorted instantly by AI compatibility. Review strengths, skill gaps, and custom summaries generated by Groq. Shortlist or hire in one click with email notifications.
          </p>
          <ul className="space-y-2 text-xs font-bold text-slate-500 pt-2">
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-teal-600" />
              <span>Automated AI Candidate Ranking</span>
            </li>
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-teal-600" />
              <span>In-depth Strength & Weakness analysis</span>
            </li>
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-teal-600" />
              <span>Interactive hiring workflows</span>
            </li>
          </ul>
        </div>

        {/* Candidate Card */}
        <div className="skeuo-card p-8 space-y-4">
          <div className="w-12 h-12 rounded-xl bg-blue-500/10 flex items-center justify-center text-blue-500">
            <GraduationCap className="w-6 h-6" />
          </div>
          <h3 className="text-2xl font-extrabold">For Job Seekers</h3>
          <p className="text-sm text-slate-500 leading-relaxed">
            Upload your PDF or DOCX resume to auto-generate a structured profile. Instantly unlock personalized job matches, explore skill gaps compared to listing requirements, and view guided upskilling paths.
          </p>
          <ul className="space-y-2 text-xs font-bold text-slate-500 pt-2">
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-blue-500" />
              <span>Drag-and-drop resume parsing</span>
            </li>
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-blue-500" />
              <span>Semantic job recommendations</span>
            </li>
            <li className="flex items-center gap-2">
              <UserCheck className="w-4 h-4 text-blue-500" />
              <span>Skill gap learning recommendations</span>
            </li>
          </ul>
        </div>

      </div>

    </div>
  );
}
