# Generated by Django 4.2.30 on 2026-06-18 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='behance',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='codechef',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='codeforces',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='dribbble',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='hackerrank',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='kaggle',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='leetcode',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='personal_website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='resume_website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
