# Generated by Django 4.2.30 on 2026-06-18 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_jobseekerprofile_behance_jobseekerprofile_codechef_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='certifications',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='codechef',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='codeforces',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='dribbble',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='hackerrank',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='kaggle',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='leetcode',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='personal_website',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume_website',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='cover_banner',
            field=models.ImageField(blank=True, null=True, upload_to='cover_banners/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='is_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(default='Intermediate', max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_list', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('technologies_used', models.JSONField(blank=True, default=list)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('live_demo_link', models.URLField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, default=list)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects_list', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=500)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_list', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests_list', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hobbies_list', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('company_name', models.CharField(max_length=150)),
                ('employment_type', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=150)),
                ('college', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=150)),
                ('cgpa', models.CharField(blank=True, max_length=50, null=True)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='users.jobseekerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('issuing_organization', models.CharField(max_length=150)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=150, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications_list', to='users.jobseekerprofile')),
            ],
        ),
    ]
